### ISSUE TITLE
Add release process for new mkdocs website/docs

### ISSUE THREAD

**Issue by csantanapr** [knative/release#14]
The current process for cutting the docs release is using hugo and is documented here https://knative.dev/help/maintainer/docs-release-process/

For release 0.23 will use the current process which the pointers are in #10 

The new process will use mkdocs and the steps will be updated.

@vaikas asked that the process to be documented in this repo, this way the person being the release's lead can handle it and perhaps we add more automation to make it dead simple to cut it.

For release 0.24 will use the new mkdocs process

Both releases 0.23 and 0.24 will be done by someone from dux WG, hopefully by 0.25 is a bot doing it.

**Comment by vaikas** [comment]
@csantanapr we're <2 weeks away from pkg cut, so just checking in on the status of this.

**Comment by psschwei** [comment]
mkdocs process is described here: https://github.com/knative/docs/blob/main/contribute-to-docs/docs-release-process.md

Seems like it should be easy enough to add this into the release train (currently, docs are listed as an [exception](https://github.com/knative/release/blob/cbcfce90f152f6c929df0271bf214a3de439a5d5/TIMELINE.md#exceptions) for the release process)...

**Comment by psschwei** [comment]
This was done in #145
