### ISSUE TITLE
Add badge to operator in release checklist template

### ISSUE THREAD

**Issue by kvmware** [knative/release#207]
add a version badge to last stage `Talk to Vincent (Operator WG Lead) and have him cut (or help you cut) the knative/operator` check list item

**Comment by dprotaso** [comment]
@pradnyavmw are you still working on this issue?

**Comment by dprotaso** [comment]
@pradnyavmw are you still working on this issue?

**Comment by pradnyavmw** [comment]
I think its done - we can see the badge [here](https://github.com/knative/release/blob/main/.github/ISSUE_TEMPLATE/release-checklist.md)

**Comment by dprotaso** [comment]
great - thanks
