### ISSUE TITLE
Migrate TIMELINE info to the checklist template.

### ISSUE THREAD

**Issue by kvmware** [knative/release#208]
- Remove the TIMELINE.md once that is done so we have one source of truth.
- Add any paper cut fixes you experienced during your release lead time.
- Add a checklist item for people to do ^ ie: improve the process

**Comment by dprotaso** [comment]
@kvmware @pradnyavmw is this covered by https://github.com/knative/release/pull/219 ?

**Comment by pradnyavmw** [comment]
#219 covers first two.

**Comment by kvmware** [comment]
@pradnyavmw you want to add the last lil checklist? If not i can get to it no problem

**Comment by pradnyavmw** [comment]
Added the checklist item - https://github.com/knative/release/pull/222

**Comment by dprotaso** [comment]
thanks @pradnyavmw!
